[phases.setup]
aptPkgs = [
  "wget",
  "gnupg",
  "xvfb",
  "unzip",
  "fonts-liberation",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libatspi2.0-0",
  "libcups2",
  "libdbus-1-3",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libwayland-client0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxkbcommon0",
  "libxrandr2",
  "xdg-utils"
]

[phases.install]
cmds = [
  "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -",
  "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list",
  "apt-get update",
  "apt-get install -y google-chrome-stable",
  "pip install -r requirements.txt"
]

[start]
cmd = "Xvfb :99 -screen 0 1024x768x16 & export DISPLAY=:99 && python main.py"
